#housing price prediction project

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [16]:
data=pd.read_csv("housing.csv")

In [17]:
data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [22]:
# price is the y for us here means it is used for price prediction whereas other other attributes are varibales /data points

In [23]:
#data preprocessing

In [24]:
# we are converting all the categorical variables for model in numerical

In [25]:
#yes/no columns into 1 or 0

In [26]:
binary_cols=[
    'mainroad',
    'guestroom',
    'basement',
    'hotwaterheating',
    'airconditioning',
    'prefarea',
    'furnishingstatus'
]

for col in binary_cols:
    data[col]=data[col].map({'yes':1,'no':0})

In [27]:
data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,NaN
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,NaN
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,NaN
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,NaN
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,1,0,1,0,0,2,0,NaN
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,NaN
542,1750000,3620,2,1,1,1,0,0,0,0,0,0,NaN
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,NaN
544,1750000,3850,3,1,2,1,0,0,0,0,0,0,NaN

In [28]:
#funished stauts

In [29]:
data=pd.get_dummies(data,
                    columns=['furnishingstatus'],
                    drop_first=True)

In [30]:
data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea
0,13300000,7420,4,2,3,1,0,0,0,1,2,1
1,12250000,8960,4,4,4,1,0,0,0,1,3,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1
3,12215000,7500,4,2,2,1,0,1,0,1,3,1
4,11410000,7420,4,1,2,1,1,1,0,1,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,1,0,1,0,0,2,0
541,1767150,2400,3,1,1,0,0,0,0,0,0,0
542,1750000,3620,2,1,1,1,0,0,0,0,0,0
543,1750000,2910,3,1,1,0,0,0,0,0,0,0
544,1750000,3850,3,1,2,1,0,0,0,0,0,0

In [31]:
#build the model

In [32]:
x=data.drop('price',axis=1)
y=data['price']

In [33]:
#ml library

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    x,y,
    test_size=0.2,
    random_state=42
)

In [38]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [39]:
y_pred=model.predict(X_test)

In [40]:
y_pred

array([5398919.06668406, 7065403.52242257, 2993803.65442489,
       4535814.37095637, 3053270.46119634, 3709351.46814548,
       5440532.08436119, 6228231.2637049 , 2882007.07052161,
       2341077.46202216, 9669446.99384903, 2968606.34038989,
       3313473.96276161, 3298076.7146539 , 3917562.61502005,
       5451316.51696925, 2935783.76577867, 5020968.01587435,
       4611901.50853052, 3459716.25356269, 6031175.37726022,
       5858126.13664539, 2900858.8451071 , 5004989.10270268,
       5250383.45099946, 7582448.67436233, 3446590.61322786,
       5039916.00815844, 8051720.01234679, 3173494.27554285,
       6479223.19419278, 3527946.31942094, 6553367.01960289,
       4111301.41589294, 3752397.72547943, 5797499.44418857,
       4816747.63555382, 4616670.38819151, 3334907.08797079,
       4389155.37405231, 4503752.98075596, 3704757.77375415,
       7046386.68164143, 3784673.66996625, 3637999.13588582,
       4488238.10842619, 6736670.12525002, 3967749.94181508,
       3947022.79857926, 3676476.49203112, 7582179.3974598 ,
       2994027.85942395, 4127906.99099909, 4439286.85665633,
       3917601.79435045, 2390996.66907263, 7805079.77215151,
       3109351.61723692, 4150562.82933444, 2936753.13208149,
       4828590.52577274, 3743006.71726216, 5115053.71165292,
       4455918.24919388, 4944648.69000967, 4639788.83339262,
       7064190.54623989, 3686983.42054879, 6210246.83138142,
       6085588.0834683 , 4984762.92276008, 5114382.48073894,
       4277664.61215053, 7844875.09154106, 3727326.76667104,
       5451567.60750375, 3896621.81455448, 4623232.42138787,
       4594058.46460165, 4404327.90930476, 7605493.96891578,
       4003591.54394836, 6338956.69516695, 5623078.2362192 ,
       2942954.260402  , 7100308.39419828, 2777526.26986989,
       3606390.78764312, 7857467.10926581, 8148008.24986404,
       3170979.95059087, 5759976.95269716, 3328975.47319239,
       3745176.90356   , 7448908.41696047, 4548880.80144109,
       5100132.4404321 , 6689128.02329719, 5157394.57749555,
       5940429.18752695, 3803914.71574645, 6288549.02496795,
       3671756.15907521, 5976948.85744618, 4973484.86770153,
       4099429.25230373, 7062596.90795641, 6373900.60348399,
       6237976.55539989])

In [42]:
from sklearn.metrics import r2_score,mean_absolute_error

In [43]:
print("R2 score :", r2_score(y_test,y_pred))
print("MAE: " , mean_absolute_error(y_test,y_pred))

R2 score : 0.6437296086614115
MAE:  979112.2162187377